# Generated by Django 4.2 on 2024-05-13 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('overview', models.TextField(verbose_name='Описание')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='service_list/')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('category', models.ForeignKey(default='000', on_delete=django.db.models.deletion.SET_DEFAULT, to='service_list.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'обследование',
                'verbose_name_plural': 'обследование',
            },
        ),
    ]
