# Generated by Django 4.2 on 2024-05-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_list', '0003_product_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='time_to_session',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='время на сеанс'),
        ),
    ]
