# Generated by Django 4.2 on 2024-05-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_list', '0004_product_time_to_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='overview_big',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='overview',
            field=models.TextField(verbose_name='Короткое описание'),
        ),
    ]
