# Generated by Django 4.2 on 2024-05-16 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_list', '0005_product_overview_big_alter_product_overview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='time_to_session',
        ),
    ]
