# Generated by Django 4.2 on 2024-05-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_list', '0006_remove_product_time_to_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='overview_big',
            field=models.TextField(default='Для записи позвоните по номеру 8-800-555-35-35', verbose_name='Полное описание'),
        ),
    ]
